# Generated by Django 2.1.5 on 2019-01-20 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passRate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('failRate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('enrollment', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('theClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Classes')),
            ],
        ),
    ]
